name: Deploy to EC2

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /opt/c8-datalake
            echo "Pull latest changes"
            git pull origin master
            echo "Stop Docker"
            sudo docker compose down
            echo "Clean Docker"
            sudo docker system prune -af --volumes
            echo "Start Docker"
            sudo docker compose up -d --build
            echo "Upload logs"
            bash upload-logs.sh
            echo "Cleanup"
            bash clean-docker.sh
